/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-15 12:20:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.petSitter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class petSitterApply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/petSitter/../common/footer.jsp", Long.valueOf(1571126826997L));
    _jspx_dependants.put("/views/petSitter/../common/header.jsp", Long.valueOf(1571142043502L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tform{\r\n");
      out.write("\t\t margin: 50px 50px 50px 500px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- petSitter 지원 페이지 -->\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');

String root = request.getContextPath();


      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>leopet || Home</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"img/favicon.png\">\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root );
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- animate CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root );
      out.write("/css/animate.css\">\r\n");
      out.write("    <!-- owl carousel CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root );
      out.write("/css/owl.carousel.min.css\">\r\n");
      out.write("    <!-- themify CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root );
      out.write("/css/themify-icons.css\">\r\n");
      out.write("    <!-- flaticon CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root );
      out.write("/css/flaticon.css\">\r\n");
      out.write("    <!-- font awesome CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root );
      out.write("/css/magnific-popup.css\">\r\n");
      out.write("    <!-- style CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root );
      out.write("/css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("       footer{\r\n");
      out.write("          width:cover;\r\n");
      out.write("          height:900px;\r\n");
      out.write("          !important;\r\n");
      out.write("       }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--::header part start::-->\r\n");
      out.write("    <header class=\"header_area\">\r\n");
      out.write("        <div class=\"sub_header\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                  <div class=\"col-4 col-md-4 col-xl-6\">\r\n");
      out.write("                      <div id=\"logo\">\r\n");
      out.write("                          <a href=\"index.jsp\"><img src=\"");
      out.print(root );
      out.write("/img/pett.png\"  width = \"400px\" height = \"125px\" alt=\"\" title=\"\" /></a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-8 col-md-8 col-xl-6 \">\r\n");
      out.write("                      <div class=\"sub_header_social_icon float-right\">\r\n");
      out.write("                      \r\n");
      out.write("                        <!-- <a href=\"#\"><i class=\"flaticon-phone\"></i>+02 213 - 256 (365)</a> -->\r\n");
      out.write("                        <a href=\"views/user/LoginPage.jsp\" class=\"btn_1 d-none d-md-inline-block\">로그인</a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"main_menu\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("                            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                                <i class=\"ti-menu\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"collapse navbar-collapse justify-content-center\" id=\"navbarSupportedContent\">\r\n");
      out.write("                                <ul class=\"navbar-nav\">\r\n");
      out.write("                                    <li class=\"nav-item active\">\r\n");
      out.write("                                        <a class=\"nav-link active\" href=\"index.html\"></a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item\">\r\n");
      out.write("                                        <a href=\"index.jsp\" class=\"nav-link\">소개</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item\">\r\n");
      out.write("                                        <a href=\"views/diary/insertDiary.jsp\" class=\"nav-link\">돌봄일지</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item\">\r\n");
      out.write("                                        <a href=\"views/petSitter/petSitterApply.jsp\" class=\"nav-link\">펫 시터 지원</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                               펫 시터 예약\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"views/petsitterreservation/petSitterSearch.jsp\">방문 펫 시터 예약</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"single-blog.html\">가정집 펫시터 예약</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item\">\r\n");
      out.write("                                        <a href=\"blog.html\" class=\"nav-link\">커뮤니티</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"nav-item\">\r\n");
      out.write("                                        <a href=\"views/serviceCenter/\" class=\"nav-link\">고객센터</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("   </body>\r\n");
      out.write(" </html>");
      out.write("\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<form>\r\n");
      out.write("\t<h1>펫시터 지원서</h1><br><br>\r\n");
      out.write("\t<textarea cols=\"80\" rows=\"6\" style=\"resize:none\" name=\"textarea\">본인은 아래의 [개인정보 수집 및 이용에 관한 동의]를 잘 읽어 보았으며, 최종적으로 지원서를 작성하는 경우 위 내용에 동의하는 것으로 인정합니다. *\r\n");
      out.write("1. 목적 : 지원자 개인 식별, 지원의사 확인 2. 항목 : 지원자 성명, 휴대폰번호 및 해당 신청서에서 수집된 정보 3. 보유기간 : 해당 지원자 모집 종료 후 1년간 보유, 이용됩니다. 4. 동의를 거부할 권리 및 동의 거부에 따른 불이익 : 지원자는 위 내용에 대해서 동의를 하지 않을 권리가 있으며 지원자가 개인정보의 삭제를 요청하는 경우 지체없이 이를 삭제합니다.\r\n");
      out.write("    </textarea><br>\r\n");
      out.write("    <input type=\"checkbox\" id=\"agree\" value=\"a\">\r\n");
      out.write("    <label for=\"small\">네, 동의합니다.</label>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<h4>주거 공간</h4>\r\n");
      out.write("    <input type=\"radio\" id=\"apart\" name=\"residence\" value=\"A\" checked>\r\n");
      out.write("    <label for=\"apart\">아파트</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"villa\" name=\"residence\" value=\"V\">\r\n");
      out.write("    <label for=\"villa\">빌라</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"detachedHouse\" name=\"residence\" value=\"D\">\r\n");
      out.write("    <label for=\"detachedHouse\">단독 주택</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"etc\" name=\"residence\" value=\"E\">\r\n");
      out.write("    <label for=\"etc\">기타</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("\t<h4>직업</h4>\r\n");
      out.write("    <input type=\"radio\" id=\"jobSeekers\" name=\"job\" value=\"J\" checked>\r\n");
      out.write("    <label for=\"jobSeekers\">취업준비생</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"houseWife\" name=\"job\" value=\"H\">\r\n");
      out.write("    <label for=\"houseWife\">주부</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"officeWorkers\" name=\"job\" value=\"D\">\r\n");
      out.write("    <label for=\"officeWorkers\">직장인</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"etc\" name=\"job\" value=\"E\">\r\n");
      out.write("    <label for=\"etc\">기타</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("\t<h4>가족 동거 유무</h4>\r\n");
      out.write("\t<input type=\"radio\" id=\"yFamily\" name=\"family\" value=\"y\" checked>\r\n");
      out.write("    <label for=\"yFamily\">예</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"nFamily\" name=\"family\" value=\"n\">\r\n");
      out.write("    <label for=\"nFamily\">아니오</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("\t<h4>반려 동물 유무</h4>\r\n");
      out.write("\t<input type=\"radio\" id=\"yPet\" name=\"pet\" value=\"y\" checked>\r\n");
      out.write("    <label for=\"yPet\">예</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"nPet\" name=\"pet\" value=\"n\">\r\n");
      out.write("    <label for=\"nPet\">아니오</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("\t<h4>대형견 가능 여부</h4>\r\n");
      out.write("\t<input type=\"radio\" id=\"yBig\" name=\"big\" value=\"y\" checked>\r\n");
      out.write("    <label for=\"yBig\">예</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"nSmall\" name=\"big\" value=\"n\">\r\n");
      out.write("    <label for=\"nSmall\">아니오</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("\t<h4>투약 가능 여부</h4>\r\n");
      out.write("\t<input type=\"radio\" id=\"yMedicine\" name=\"medicine\" value=\"y\" checked>\r\n");
      out.write("    <label for=\"yMedicine\">예</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"nMedicine\" name=\"medicine\" value=\"n\">\r\n");
      out.write("    <label for=\"nMedicine\">아니오</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("\t<h4>노령견 케어 가능 여부</h4>\r\n");
      out.write("\t<input type=\"radio\" id=\"yOld\" name=\"old\" value=\"y\" checked>\r\n");
      out.write("    <label for=\"yOld\">예</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"nOld\" name=\"old\" value=\"n\">\r\n");
      out.write("    <label for=\"nOld\">아니오</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("\t<h4>환자견 케어 가능 여부</h4>\r\n");
      out.write("\t<input type=\"radio\" id=\"yPatient\" name=\"patient\" value=\"y\" checked>\r\n");
      out.write("    <label for=\"yPatient\">예</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"nPatient\" name=\"patient\" value=\"n\">\r\n");
      out.write("    <label for=\"nPatient\">아니오</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("\t<h4>반려동물 관련 자격증 보유 여부</h4>\r\n");
      out.write("\t<input type=\"radio\" id=\"yCertificate\" name=\"certificate\" value=\"y\" checked>\r\n");
      out.write("    <label for=\"yCertificate\">예</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"nCertificate\" name=\"certificate\" value=\"n\">\r\n");
      out.write("    <label for=\"nCertificate\">아니오</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <h4>반려견을 얼마나 키워보셨나요?(최근 5년 이내)</h4>\r\n");
      out.write("    <input type=\"radio\" id=\"one\" name=\"term\" value=\"o\" checked>\r\n");
      out.write("    <label for=\"one\">1년 미만</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"three\" name=\"term\" value=\"t\">\r\n");
      out.write("    <label for=\"three\">1년 ~ 3년</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"five\" name=\"term\" value=\"f\">\r\n");
      out.write("    <label for=\"five\">3년 ~ 5년</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"noExp\" name=\"term\" value=\"n\">\r\n");
      out.write("    <label for=\"noExp\">경험 없음</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <h4>어느정도 크기의 강아지까지 돌봄이 가능하신가요? </h4>\r\n");
      out.write("    <input type=\"radio\" id=\"small\" name=\"size\" value=\"s\" checked>\r\n");
      out.write("    <label for=\"small\">소형견까지</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"medium\" name=\"size\" value=\"m\">\r\n");
      out.write("    <label for=\"medium\">중형견까지</label>&nbsp;&nbsp;\r\n");
      out.write("    <input type=\"radio\" id=\"large\" name=\"size\" value=\"l\">\r\n");
      out.write("    <label for=\"large\">대형견까지</label>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <textarea cols=\"45\" rows=\"3\" style=\"resize:none\" name=\"textarea\">이제까지 본인에 의해 작성된 모든 정보는 사실임을 확인하였으며, 사실 내용과 다르게 기재하였을 경우 어떤 불이익도 감수 하겠습니다. *\r\n");
      out.write("    </textarea><br>\r\n");
      out.write("    <input type=\"checkbox\" id=\"agree\" value=\"a\">\r\n");
      out.write("    <label for=\"small\">네, 동의합니다.</label>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\t<input type=\"submit\" value=\"제출하기\">\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("\t<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("       footer{\r\n");
      out.write("          width:cover;\r\n");
      out.write("          height:500px;\r\n");
      out.write("          !important;\r\n");
      out.write("       }\r\n");
      out.write("</style>\r\n");
      out.write("    <!-- jquery plugins here-->\r\n");
      out.write("    <!-- jquery -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-1.12.1.min.js\"></script>\r\n");
      out.write("    <!-- popper js -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/popper.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap js -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- counterup js -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <!-- waypoints js -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/waypoints.min.js\"></script>\r\n");
      out.write("    <!-- easing js -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <!-- particles js -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <!-- custom js -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/custom.js\"></script>\r\n");
      out.write("    <link rel=\"icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/img/favicon.png\">\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- animate CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/animate.css\">\r\n");
      out.write("    <!-- owl carousel CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/owl.carousel.min.css\">\r\n");
      out.write("    <!-- themify CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/themify-icons.css\">\r\n");
      out.write("    <!-- flaticon CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/flaticon.css\">\r\n");
      out.write("    <!-- font awesome CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/magnific-popup.css\">\r\n");
      out.write("    <!-- style CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- footer part start-->\r\n");
      out.write("    <footer class=\"footer_area padding_top\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- footer part end-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
